# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
list_change <- function(x, Id) {
    .Call('_floodmap_list_change', PACKAGE = 'floodmap', x, Id)
}

#' @export
listlen <- function(x) {
    .Call('_floodmap_listlen', PACKAGE = 'floodmap', x)
}

